### ISSUE TITLE
Dead repo?

### ISSUE THREAD

**Issue by FrederikBolding** [migregorio/OMDbSharp#1]
I've been working a bit on my own fork, and was wondering if you were requesting pull requests, or if the repo is completely dead?

**Comment by migregorio** [comment]
Yes. Please feel free. Although I haven't updated it lately, the repo is open for pull requests.

**Comment by FrederikBolding** [comment]
@migregorio I was gonna offer to take over the repo if you aren't interested in updating, would you rather have me do pull requests or?

**Comment by migregorio** [comment]
I'm happy to carry on with it. Thanks, Frederik! Please feel free to do pull requests.
