### ISSUE TITLE
.ReadAsAsync error

### ISSUE THREAD

**Issue by noahgrostefon** [migregorio/OMDbSharp#2]
I'm getting this error in the Omdb.cs Class. 

'System.Net.Http.HttpContent' does not contain a definition for 'ReadAsAsync' and no extension method 'ReadAsAsync' accepting a first argument of type 'System.Net.Http.HttpContent' could be found (are you missing a using directive or an assembly reference?)

**Comment by migregorio** [comment]
Are you still getting this error, or did you work around it? If you're still experiencing the problem, feel free to reopen the issue.
